ProyectoCRUD/Controllers/MatenimientoController.cs
using ProyectoCRUD.Models;
using ProyectoCRUD.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoCRUD.Controllers
{
    public class MatenimientoController : Controller
    {
            // GET: TipoProducto
            public ActionResult Index()
            {
                List<ListarMantenimiento> list;
                using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
                {
                    list = (from b in bd.TB_Mantenimientos
                            select new ListarMantenimiento
                            {
                                ID = b.Mantenimiento_ID,
                                Descripcion= b.Mantenimiento_Descripcion,
                                KM = b.Mantenimiento_KM,
                            }).ToList();
                }
                return View(list);
            }
            public ActionResult Nuevo()
            {
                return View();
            }
        [HttpPost]
        public ActionResult Nuevo(MantenimientoViewModel TP)
        {
            try
            {
                //Validación Datos
                if (ModelState.IsValid)
                {
                    //Almacenamiento DATOS DB
                    using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
                    {
                        var tprod = new TB_Mantenimientos();
                        tprod.Mantenimiento_Descripcion= TP.Descripcion;
                        tprod.Mantenimiento_KM = TP.KM;
                        bd.TB_Mantenimientos.Add(tprod);
                        bd.SaveChanges();
                    }
                    return Redirect("~/Matenimiento/");
                }

                return View(TP);
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

        }
        public ActionResult Editar(int id)
        {
            MantenimientoViewModel model = new MantenimientoViewModel();
            using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
            {
                var Tprod = bd.TB_Mantenimientos.Find(id);//obtenemos registro por medio de id
                model.ID = Tprod.Mantenimiento_ID;
                model.Descripcion = Tprod.Mantenimiento_Descripcion;
                model.KM= Tprod.Mantenimiento_KM;
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Editar(MantenimientoViewModel TP)
        {
            try
            {
                //validar datos
                if (ModelState.IsValid)
                {
                    //guardamos datos en bd
                    using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
                    {
                        var Tprod = bd.TB_Mantenimientos.Find(TP.ID);//obtenemos registro por medio de id
                        Tprod.Mantenimiento_Descripcion = TP.Descripcion;
                        Tprod.Mantenimiento_KM = TP.KM;
                        //editamos registro
                        bd.Entry(Tprod).State = EntityState.Modified;
                        bd.SaveChanges();
                    }

                    return Redirect("~/Matenimiento/");
                }

                return View(TP);
            }

            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

        }
        [HttpPost]
        public ActionResult Eliminar(int id)
        {

            MantenimientoViewModel model = new MantenimientoViewModel();
            using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
            {
                var tProd = bd.TB_Mantenimientos.Find(id);//obtengo entidad con id

                bd.TB_Mantenimientos.Remove(tProd);

                bd.SaveChanges();

            }
            return Content("ok");
        }
    }
}

ProyectoCRUD/Views/Matenimiento/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<center><h2>Datos Mantenimiento</h2></center>
<!-- Boton Nuevo  -->
<div class=" row" style="text-align:right; padding:5px">
    <div class="col-md-12">
        <input type="button" class="btn btn-primary" value="Nuevo" onclick="document.location.href='@Url.Content("~/Matenimiento/Nuevo")'" />
    </div>
</div>
<!-- Creo tabla  -->
<div class="row">
    <div class="col-md-12">

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Modo</th>
                    <th>Editar/Eliminar</th>
                </tr>
            </thead>
            <!-- Recorro el modelo para imprimir datos -->
            @foreach (var elemento in Model)
            {
        <tr>
            <td>@elemento.ID</td>
            <td>@elemento.Descripcion</td>
            <td>@elemento.KM</td>
            <td>
                <!-- Botones Editar Eliminar  -->
                <input type="button" onclick="document.location.href='@Url.Content("~/Matenimiento/Editar/"+elemento.ID)'" value="Editar" class="btn btn-default" />
                <div style="text-align: justify;">
                    <input class="btn btn-danger" onclick="jsEliminar(@elemento.ID);" type="button" value="Eliminar" />
                </div>
            </td>
        </tr>
            }
        </table>
    </div>
</div>
<script>
function jsEliminar(id) {
        if (confirm("Quieres Eliminar El Registro?")) {
            url = "@Url.Content("~/Matenimiento/Eliminar")" + "/"+id; //metodo Eliminar Controller

            $.post(url, function (data) {

            if (data=="ok") {
            document.location.href = "@Url.Content("~/Matenimiento/")"
            console.log("Exito");
            } else {
            alert("No se pudo Eliminar El registro");
            }

            })
            }
            }
</script>

ProyectoCRUD/Views/Matenimiento/Nuevo.cshtml
@model ProyectoCRUD.Models.ViewModels.MantenimientoViewModel
@{
    ViewBag.Title = "Nuevo";
}

<h2>Nuevo</h2>
<!-- usamos helper para crear el formulario de tipo Post  -->
@using (Html.BeginForm("Nuevo", "Matenimiento", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <!-- Creo label   -->
                @Html.LabelFor(p => p.Descripcion):
                <!-- Creo textbox  -->
                @Html.TextBoxFor(p => p.Descripcion, "", new { @class = "form-control" })
                <!-- para mostrar mensaje de error  -->
                @Html.ValidationMessageFor(p => p.Descripcion, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <!-- Creo label   -->
                @Html.LabelFor(p => p.KM):
                <!-- Creo textbox  -->
                @Html.TextBoxFor(p => p.KM, "", new { @class = "form-control" })
                <!-- para mostrar mensaje de error  -->
                @Html.ValidationMessageFor(p => p.KM, null, new { @class = "text-danger" })
            </div>
            <div style="text-align:center">
                <input type="submit" class="btn btn-primary" value="Guardar" />
            </div>
        </div>
    </div>
}