ProyectoCRUD/Models/ViewModels/TipoProductoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProyectoCRUD.Models.ViewModels
{
    public class TipoProductoViewModel
    {
        public int ID { get; set; }
        [Required]
        [Display(Name = "Tipo Producto")]
        //valida el numero de caracteres igual a varchar(50) de nuestra bd
        [StringLength(25)]
        public string TipoProducto { get; set; }
    }
}

ProyectoCRUD/Controllers/TipoProductoController.cs
using ProyectoCRUD.Models;
using ProyectoCRUD.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoCRUD.Controllers
{
    public class TipoProductoController : Controller
    {
        // GET: TipoProducto
        public ActionResult Index()
        {
            List<ListarTipoProducto> list;
            using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
            {
                list = (from b in bd.TB_TipoProductos
                        select new ListarTipoProducto
                        {
                            ID = b.TipoP_ID,
                            TipoProducto = b.TipoP_Tipo
                        }).ToList();
            }
            return View(list);
        }
        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(TipoProductoViewModel TP)
        {
            try
            {
                //Validación Datos
                if (ModelState.IsValid)
                {
                    //Almacenamiento DATOS DB
                    using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
                    {
                        var tprod = new TB_TipoProductos();
                        tprod.TipoP_Tipo = TP.TipoProducto;
                        bd.TB_TipoProductos.Add(tprod);
                        bd.SaveChanges();
                    }
                    return Redirect("~/TipoProducto/");
                }

                return View(TP);
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

        }
        public ActionResult Editar(int id)
        {
            TipoProductoViewModel model = new TipoProductoViewModel();
            using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
            {
                var Tprod = bd.TB_TipoProductos.Find(id);//obtenemos registro por medio de id
                model.ID = Tprod.TipoP_ID;
                model.TipoProducto = Tprod.TipoP_Tipo;
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Editar(TipoProductoViewModel TP)
        {
            try
            {
                //validar datos
                if (ModelState.IsValid)
                {
                    //guardamos datos en bd
                    using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
                    {
                        var Tprod = bd.TB_TipoProductos.Find(TP.ID);//obtenemos registro por medio de id
                        Tprod.TipoP_Tipo = TP.TipoProducto;
                        //editamos registro
                        bd.Entry(Tprod).State = EntityState.Modified;
                        bd.SaveChanges();
                    }

                    return Redirect("~/TipoProducto/");
                }

                return View(TP);
            }

            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

        }
        [HttpPost]
        public ActionResult Eliminar(int id)
        {

            TipoProductoViewModel model = new TipoProductoViewModel();
            using (DB_Parcial2Entities1 bd = new DB_Parcial2Entities1())
            {
                var tProd = bd.TB_TipoProductos.Find(id);//obtengo entidad con id

                bd.TB_TipoProductos.Remove(tProd);

                bd.SaveChanges();

            }
            return Content("ok");
        }
    }
}

ProyectoCRUD/Views/TipoProducto/Editar.cshtml
@model  ProyectoCRUD.Models.ViewModels.TipoProductoViewModel
@{
    ViewBag.Title = "Nuevo";
}
<h2>Nuevo</h2>

<!-- usamos helper para crear el formulario de tipo Post  -->
@using (Html.BeginForm("Editar", "TipoProducto", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(p => p.ID);
            <div class="form-group">
                <!-- Creo label   -->
                @Html.LabelFor(p => p.TipoProducto):
                <!-- Creo textbox  -->
                @Html.TextBoxFor(p => p.TipoProducto, "", new { @class = "form-control" })
                <!-- para mostrar mensaje de error  -->
                @Html.ValidationMessageFor(p => p.TipoProducto, null, new { @class = "text-danger" })
            </div>

            <div style="text-align:center">
                <input type="submit" class="btn btn-primary" value="Guardar" />
            </div>
        </div>
    </div>
}

ProyectoCRUD/Views/TipoProducto/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<center><h2>Datos Tipo Producto</h2></center>
<!-- Boton Nuevo  -->
<div class=" row" style="text-align:right; padding:5px">
    <div class="col-md-12">
        <input type="button" class="btn btn-primary" value="Nuevo" onclick="document.location.href='@Url.Content("~/TipoProducto/Nuevo")'" />
    </div>
</div>
<!-- Creo tabla  -->
<div class="row">
    <div class="col-md-12">

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Tipo Producto</th>
                    <th>Editar/Eliminar</th>
                </tr>
            </thead>
            <!-- Recorro el modelo para imprimir datos -->
            @foreach (var elemento in Model)
            {
                <tr>
                    <td>@elemento.ID</td>
                    <td>@elemento.TipoProducto</td>
                    <td>
                        <!-- Botones Editar Eliminar  -->
                        <input type="button" onclick="document.location.href='@Url.Content("~/TipoProducto/Editar/"+elemento.ID)'" value="Editar" class="btn btn-default" />
                        <div style="text-align: justify;">
                            <input class="btn btn-danger" onclick="jsEliminar(@elemento.ID);" type="button" value="Eliminar" />
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
<script/>
    function jsEliminar(id) {
        if (confirm("Quieres Eliminar El Registro?")) {
            url = "@Url.Content("~/TipoProducto/Eliminar")" + "/"+id; //metodo Eliminar Controller

            $.post(url, function (data) {

            if (data=="ok") {
            document.location.href = "@Url.Content("~/TipoProducto/")"
            console.log("Exito");
            } else {
            alert("No se pudo Eliminar El registro");
            }

            })
            }
            }
            </script/>

ProyectoCRUD/Views/TipoProducto/Nuevo.cshtml
@model ProyectoCRUD.Models.ViewModels.TipoProductoViewModel
@{
    ViewBag.Title = "Nuevo";
}

<h2>Nuevo</h2>
<!-- usamos helper para crear el formulario de tipo Post  -->
@using (Html.BeginForm("Nuevo", "TipoProducto", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <!-- Creo label   -->
                @Html.LabelFor(p => p.TipoProducto):
                <!-- Creo textbox  -->
                @Html.TextBoxFor(p => p.TipoProducto, "", new { @class = "form-control" })
                <!-- para mostrar mensaje de error  -->
                @Html.ValidationMessageFor(p => p.TipoProducto, null, new { @class = "text-danger" })
            </div>
            <div style="text-align:center">
                <input type="submit" class="btn btn-primary" value="Guardar" />
            </div>
        </div>
    </div>
}